services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8001
    
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: terminal
      POSTGRES_USER: terminaluser
      POSTGRES_PASSWORD: kb971033
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8081:8081"

volumes:
  pgdata:
