# Generated by Django 5.1.3 on 2025-02-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
        ('hr', '0005_employee_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='hr.company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='hr.company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cashflow.wallet', verbose_name='Кошелёк'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название кошелька'),
        ),
    ]
