# Generated by Django 5.1.3 on 2025-01-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('primary_phone', models.CharField(help_text='Введите телефон в формате +79991234567', max_length=15, unique=True, verbose_name='Основной телефон клиента')),
                ('backup_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Резервный телефон')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
