# Generated by Django 5.1.3 on 2025-02-15 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_primary_phone_and_more'),
        ('hr', '0005_employee_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='hr.company', verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_phone',
            field=models.CharField(help_text='Введите телефон в формате +75551234567', max_length=15, verbose_name='Основной телефон клиента'),
        ),
    ]
