# Generated by Django 5.1.3 on 2025-01-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_activitytype_businessdirection_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cashflow.activitytype', verbose_name='Вид деятельности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание статьи'),
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cashflow.group', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название статьи'),
        ),
    ]
