# Generated by Django 5.1.3 on 2025-01-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_wallet_transaction_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
