# Generated by Django 5.1.3 on 2025-01-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0006_remove_transaction_transaction_type'),
        ('orders', '0003_order_status_orderitem_status_orderitem_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order', verbose_name='Заказ'),
        ),
    ]
