# Generated by Django 5.1.3 on 2025-01-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0007_transaction_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
    ]
