# Generated by Django 5.1.3 on 2025-01-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0010_wallet_created_at_wallet_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='group',
        ),
        migrations.AddField(
            model_name='category',
            name='operation_type',
            field=models.CharField(choices=[('income', 'Поступление'), ('expense', 'Выбытие'), ('technical_income', 'Техническое поступление'), ('technical_expense', 'Техническое выбытие')], default='income', help_text='Указывает, как обрабатывать эту категорию', max_length=20, verbose_name='Тип операции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, null=True, verbose_name='Тип транзакции'),
        ),
    ]
