# Generated by Django 5.1.3 on 2025-01-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0011_remove_category_activity_type_remove_category_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
