# Generated by Django 5.1.3 on 2025-01-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0012_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='activity_type',
            field=models.ForeignKey(blank=True, help_text='Укажите вид деятельности для данной категории', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cashflow.activitytype', verbose_name='Вид деятельности'),
        ),
    ]
