# Generated by Django 5.1.3 on 2025-01-13 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0013_category_activity_type'),
        ('orders', '0004_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order', verbose_name='Связанный заказ'),
        ),
    ]
