# Generated by Django 5.1.3 on 2025-01-13 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0014_transaction_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='activity_type',
        ),
        migrations.DeleteModel(
            name='BusinessDirection',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='operation_type',
            field=models.CharField(choices=[('income', 'Поступление'), ('expense', 'Выбытие'), ('technical_income', 'Техническое поступление'), ('technical_expense', 'Техническое выбытие')], max_length=20, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cashflow.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cashflow.wallet', verbose_name='Кошелёк'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ActivityType',
        ),
    ]
