# Generated by Django 5.1.3 on 2025-01-13 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0016_alter_transaction_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание статьи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='operation_type',
            field=models.CharField(choices=[('income', 'Поступление'), ('expense', 'Выбытие'), ('technical_income', 'Техническое поступление'), ('technical_expense', 'Техническое выбытие')], help_text='Указывает, как обрабатывать эту категорию', max_length=20, verbose_name='Тип операции'),
        ),
        migrations.AddField(
            model_name='category',
            name='activity_type',
            field=models.ForeignKey(blank=True, help_text='Укажите вид деятельности для данной категории', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cashflow.activitytype', verbose_name='Вид деятельности'),
        ),
    ]
