# Generated by Django 5.1.3 on 2025-01-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0017_activitytype_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
