# Generated by Django 5.1.3 on 2025-01-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0018_remove_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, null=True, verbose_name='Тип транзакции'),
        ),
    ]
