# Generated by Django 5.1.3 on 2025-01-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0020_remove_transaction_transaction_type'),
        ('orders', '0007_alter_order_customer_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='orders.orderitem', verbose_name='Элемент заказа'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
