# Generated by Django 5.1.3 on 2025-01-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0021_transaction_order_item_alter_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='order_item',
            new_name='reason_transaction',
        ),
    ]
