# Generated by Django 5.1.3 on 2025-01-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0022_rename_order_item_transaction_reason_transaction'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reason_transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
