# Generated by Django 5.1.3 on 2025-02-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_pricelist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bookable',
            field=models.BooleanField(default=False, verbose_name='Is Bookable'),
        ),
    ]
