# Generated by Django 5.1.3 on 2025-02-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Начало брони')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Конец брони')),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус брони')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Забронированное количество')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Начало брони (элемент)')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Конец брони (элемент)')),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус позиции')),
            ],
            options={
                'verbose_name': 'Позиция бронирования',
                'verbose_name_plural': 'Позиции бронирования',
            },
        ),
    ]
