# Generated by Django 5.1.3 on 2025-02-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='booking.booking', verbose_name='Бронирование'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='orders.orderitem', verbose_name='Позиция заказа'),
        ),
    ]
