# Generated by Django 5.1.3 on 2025-02-21 17:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_company_alter_client_primary_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateField(auto_now_add=True, verbose_name='Дата возврата')),
                ('reason', models.TextField(blank=True, verbose_name='Причина возврата')),
                ('refund_quantity', models.PositiveIntegerField(verbose_name='Количество к возврату')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма возврата')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена за единицу продукта', max_digits=10, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Скидка на единицу продукта (в денежном выражении)', max_digits=10, verbose_name='Скидка')),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('paid', 'Оплачен'), ('cancelled', 'Отменен'), ('deleted', 'Удален')], default='pending', max_length=20, verbose_name='Статус')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
