# Generated by Django 5.1.3 on 2025-02-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashflow', '0002_transaction_company_wallet_company_and_more'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='wallet',
            field=models.ForeignKey(blank=True, help_text='Кошелёк для транзакции', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.wallet', verbose_name='Кошелёк'),
        ),
        migrations.AddField(
            model_name='orderitemrefund',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.orderitem', verbose_name='Позиция заказа'),
        ),
        migrations.AddField(
            model_name='orderitemrefund',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.wallet', verbose_name='Кошелёк для возврата'),
        ),
    ]
