# Generated by Django 5.1.3 on 2025-02-02 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='subdomain',
            field=models.CharField(blank=True, help_text='Введите поддомен, состоящий только из маленьких латинских букв, цифр и дефисов.', max_length=50, null=True, unique=True),
        ),
    ]
