# Generated by Django 5.1.3 on 2025-02-15 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employeeinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 15, 8, 51, 53, 88782, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
