# Generated by Django 5.1.3 on 2025-03-28 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_created_at'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='hr.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='hr.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitemrefund',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='hr.company'),
            preserve_default=False,
        ),
    ]
