# Generated by Django 5.1.3 on 2025-01-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Завершен'), ('refunded', 'Возврат средств'), ('cancelled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
