# Generated by Django 5.1.3 on 2025-01-14 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0021_transaction_order_item_alter_transaction_date'),
        ('orders', '0007_alter_order_customer_alter_order_order_date_and_more'),
        ('products', '0003_product_unique_product_by_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена за единицу продукта', max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='wallet',
            field=models.ForeignKey(blank=True, help_text='Кошелёк для транзакции', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.wallet', verbose_name='Кошелёк'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
