# Generated by Django 5.1.3 on 2025-01-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'В процессе'), ('paid', 'Оплачен'), ('cancelled', 'Отменен'), ('deleted', 'Удален')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
