# Generated by Django 5.1.3 on 2025-01-17 14:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Скидка на единицу продукта (в денежном выражении)', max_digits=10, verbose_name='Скидка'),
        ),
    ]
