# Generated by Django 5.1.3 on 2025-01-18 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0022_rename_order_item_transaction_reason_transaction'),
        ('orders', '0015_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='wallet',
            field=models.ForeignKey(help_text='Кошелёк для транзакции', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.wallet', verbose_name='Кошелёк'),
        ),
    ]
