# Generated by Django 5.1.3 on 2025-01-18 08:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0022_rename_order_item_transaction_reason_transaction'),
        ('orders', '0018_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateField(auto_now_add=True, verbose_name='Дата возврата')),
                ('reason', models.TextField(blank=True, verbose_name='Причина возврата')),
                ('refund_quantity', models.PositiveIntegerField(verbose_name='Количество к возврату')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма возврата')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.orderitem', verbose_name='Позиция заказа')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.wallet', verbose_name='Кошелёк для возврата')),
            ],
        ),
    ]
