# Generated by Django 5.1.3 on 2025-02-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_created_at'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_by_type_per_company',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'category', 'name'), name='unique_product_name_in_category_per_company'),
        ),
    ]
