# Generated by Django 5.1.3 on 2025-02-22 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_created_at'),
        ('products', '0002_alter_pricelist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='hr.company', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('service', 'Service'), ('product', 'Product')], default='product', max_length=10, verbose_name='Product Type'),
        ),
    ]
