# Generated by Django 5.1.3 on 2025-02-22 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_created_at'),
        ('products', '0003_productinfo_company_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes_value', to='hr.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
