# Generated by Django 5.1.3 on 2025-02-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_created_at'),
        ('products', '0004_productattributevalue_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='hr.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
