# Generated by Django 5.1.3 on 2025-02-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_pricelist_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='products.product', verbose_name='Product'),
        ),
    ]
